### ISSUE TITLE
Default import/export is not treated as live binding

### ISSUE THREAD

**Issue by asapach** [rollup/rollup#1078]
Rollup doesn't treat default import/export as a live binding, meaning that changes to the export value is not reflected in the import. Example:

``` js
// --- calc.js ---
var x = 0
export {x as default}
export function inc() {
    x++
}

// --- main.js ---
import {default as x, inc} from './calc.js'
console.log(x)
inc()
console.log(x)
```

Here's a repro: [link](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QmRlZmF1bHQlMjBhcyUyMHglMkMlMjBpbmMlN0QlMjBmcm9tJTIwJy4lMkZjYWxjLmpzJyU1Q25jb25zb2xlLmxvZyh4KSU1Q25pbmMoKSU1Q25jb25zb2xlLmxvZyh4KSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjYWxjLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMHglMjAlM0QlMjAwJTVDbmV4cG9ydCUyMCU3QnglMjBhcyUyMGRlZmF1bHQlN0QlNUNuZXhwb3J0JTIwZnVuY3Rpb24lMjBpbmMoKSUyMCU3QiU1Q24lNUN0eCUyQiUyQiU1Q24lN0QlMjIlN0QlNUQlN0Q=)

---

Whereas named export works fine:

``` js
// --- calc.js ---
export var x = 0
export function inc() {
    x++
}

// --- main.js ---
import {x, inc} from './calc.js'
console.log(x)
inc()
console.log(x)
```

Here's a repro: [link](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QnglMkMlMjBpbmMlN0QlMjBmcm9tJTIwJy4lMkZjYWxjLmpzJyU1Q25jb25zb2xlLmxvZyh4KSU1Q25pbmMoKSU1Q25jb25zb2xlLmxvZyh4KSUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJjYWxjLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMHZhciUyMHglMjAlM0QlMjAwJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwaW5jKCklMjAlN0IlNUNuJTVDdHglMkIlMkIlNUNuJTdEJTIyJTdEJTVEJTdE)

**Comment by pygy** [comment]
[Here's a minimal repro](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMGZvbyUzQiU1Q25mb28lMjAlM0QlMjBmdW5jdGlvbiUyMGZvbygpJTdCJTdEJTNCJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwZm9vJTNCJTIyJTdEJTVEJTdE):

```JS
var foo;
foo = 5
export default foo;
```

Becomes (as ES2015)

```JS
var foo;
foo = 5;
var foo$1 = foo;

export default foo$1;
```

**Comment by asapach** [comment]
@pygy, in your example it exports a value instead of the binding. It's equivalent to:
```js
export default 5;
```
To fix it it needs to be:
```js
var foo;
foo = 5
export {foo as default};
```
This works in babel (e.g. `babel-register`), systemjs and webpack2. It even works in Edge browser. Rollup is the only ES6-aware tool that doesn't support it.

**Comment by pygy** [comment]
Oooh indeed, my bad. [Fixed sample](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMGZvbyUzQiU1Q25mb28lMjAlM0QlMjA1JTNCJTVDbmV4cG9ydCUyMCU3QmZvbyUyMGFzJTIwZGVmYXVsdCU3RCUzQiUyMiU3RCU1RCU3RA==).

**Comment by Rich-Harris** [comment]
The current behaviour is deliberate – my understanding (cc @eventualbuddha, who is better at this stuff than me) is that default exports are *not* live, because they're expressions rather than bindings.

**Comment by Rich-Harris** [comment]
(Or, more accurately, `export default` *does* export a binding, but it exports a binding to a synthetic name called `*default*` which can't be written to inside the exporting module – in other words by changing the value of `x` in the top example you're not actually changing the value of the default export.)

**Comment by kzc** [comment]
Babel generates a live binding for the default:

$ cat calc.js 
```js
var x = 0
export {x as default}
export function inc() {
    x++
}
```
$ babel calc.js
```js
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.inc = inc;
var x = 0;
exports["default"] = x;

function inc() {
    exports["default"] = x += 1;
}
```
$ cat main.js 
```js
import {default as x, inc} from './calc.js'
console.log(x)
inc()
console.log(x)
```
$ babel main.js
```js
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _calcJs = require('./calc.js');

var _calcJs2 = _interopRequireDefault(_calcJs);

console.log(_calcJs2['default']);
(0, _calcJs.inc)();
console.log(_calcJs2['default']);
```

**Comment by eventualbuddha** [comment]
According to [this StackOverflow answer](http://stackoverflow.com/a/39277065), default exports are sometimes bound, but not always. I've been confused about this for ages…

**Comment by Rich-Harris** [comment]
Oh for the love of–

Why? Why would it be designed that way? It means that `import foo from 'foo';` has two completely different meanings depending on the nature of `'foo'`.

I give up.

**Comment by asapach** [comment]
I've done some research on this: `*default*` local name is used in these cases (`export default ...`):
* `undefined`
* Literals (e.g. `null`, `42`, `'foo'`, etc.)
* Identifiers (e.g. `export default foo`)
* Anonymous function or class declarations/expressions (and generators)
* Other expressions

The only remaining case is named function and class declarations - and it mostly works correctly in Rollup: when functions are re-declared the last one wins ([example](http://rollupjs.org/?version=0.37.0&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBjdWJlJTIwJTdEJTIwZnJvbSUyMCcuJTJGbWF0aHMuanMnJTNCJTVDbmNvbnNvbGUubG9nKCUyMGN1YmUoJTIwNSUyMCklMjApJTNCJTIwJTJGJTJGJTIwMTI1JTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1hdGhzLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0cmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlNUNuJTdEJTVDbiU1Q25mdW5jdGlvbiUyMGN1YmUlMjAoKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAxMjUlM0IlNUNuJTdEJTIyJTdEJTVEJTdE)). There are edge cases when these named declarations get re-assigned, but they can be ignored for the sake of simplicity.

However `export { ... as default }` needs to be treated like a named export - in this instance `default` is a special name, but not a special case, and follows the same rules. `*default*` local name is never used here.

**Comment by Victorystick** [comment]
The `default` binding should be treated exactly the same as any other. The _only_ difference between it and other bindings lies in the _syntactic sugar_ that is `export default`.

The ECMAScript committee decided that there had to be some "easy" syntax, and thus the default import/export was born. (I can't find exactly where they talked about it over on https://esdiscuss.org, but this is [somewhat related](https://esdiscuss.org/topic/module-syntax).) I'm starting to wonder if we wouldn't have been better off without it.

The default declaration
```js
export default 1337;
```
is basically just a shorthand for
```js
// This variable is called *default* in the spec, just as asapach@ says.
var implicitVariable = 1337;
export { implicitVariable as default };
```

It's syntactic sugar in the same way as 
```js
import foo from 'foo';
```
is sugar for
```js
import {default as foo} from 'foo';
```

**Note** that _named_ function and class declarations are exceptions to this rule! They are not assigned to an intermediate variable, but exported as is. Compare
```js
export default class {};
// becomes
var implicit = class {};
export { implicit as default };
```
with
```js
export default class A {}
// becomes
class A {}
export { A as default };
```
The same thing applies for function declarations, which is why they can be referenced within the module.

**Comment by Rich-Harris** [comment]
> I'm starting to wonder if we wouldn't have been better off without it.

We absolutely would have been. Default exports have caused no end of problems. People get desperately confused by all the different forms of `import`/`export` declaration – imagine if we could teach people that you either import `{ names }` or `* as namespace`, and that you can export either names or declarations. As it stands, it *feels* like there's a ton of different variations you have to understand. 

Plus the confusion that arises over whether default exports are live or not. I've spent more time learning about ES modules than anyone should reasonably be expected to, and I had *no idea* that the situation is as you've described. (Marked this issue as a bug, btw.)

And then there's the interop headaches. Ostensibly, privileged default exports were meant to make adoption easier for a community that's familiar with Node modules, which is ironic as nonsense like`module.exports.default` has probably caused more friction than any other aspect of ES modules. I'm sure we could have come up with a better way of importing single-export CommonJS modules. (Though we shouldn't really call them CommonJS modules – CommonJS modules [can only have named exports](http://wiki.commonjs.org/wiki/Modules/1.1)!)

Unfortunately, we're stuck with it.

**Comment by Victorystick** [comment]
I hear you. Knew Node didn't really follow the CommonJS standard, but not that CommonJS was limited to only named exports. Would have made the whole thing much easier though.

The solution is quite easy though: stop treating `default` differently from the other bindings. Instead of
```js
$ = 'default' in $ ? $['default'] : $;

$( 'body' ).html( '<h1>Hello world!</h1>' );
```
it'll be straight on
```js
$.default( 'body' ).html( '<h1>Hello world!</h1>' );
```

**Comment by Rich-Harris** [comment]
This is fixed in 0.38

**Comment by objectkit** [comment]
Unfortunately I am encountering a similar issue, BUT... it is an uncertain edge case. I have taken the advice from above to use ``export { TARGET as default }`` rather than `` export default TARGET``, but name mangling is still happening when I import by module name.

Parent.js:
```
class Parent  {
    
}

export { Parent as default }

```

Child.js:
```
import "/Parent" // import by module name

class Child extends Parent {

}

export { Child as default }
```

then with rollup...

```
class Parent$1  {
    
}

class Child extends Parent {

}

export { Child, Parent$1 as Parent };
```

However, If I change the import to``import Parent from "/Parent"``, I get what I would have expected:

```
class Parent  {
    
}

class Child extends Parent {

}

export { Child, Parent };
```

I would have expected that importing by module name would the same affect as importing by default member. Am I mistaken?

**Comment by asapach** [comment]
`import "/Parent"` is not the same as `import Parent from "/Parent"`
In the first case you're just importing the module without any bindings - this is usually done for side effects.

**Comment by objectkit** [comment]
Cheers for the heads up! Rollup without name mangling was the side effect I was hoping for actually... I guess implicit bindings are not part of the es specification? Or is it an issue with Rollup?

**Comment by asapach** [comment]
Nope, there's no such thing as implicit bindings. In real ES modules this would throw an error. You can actually try in latest Safari or Edge under some flags.

**Comment by objectkit** [comment]
OK! Thank you! I was most definitely confused. I suspected it was a long shot. Context was a dependency resolution plugin I was considering using btw. Default imports work fine, and keep within ES spec, so Rollup === OK. Thanks @asapach 👍

**Comment by wearhere** [comment]
I think this regressed https://github.com/rollup/rollup/issues/2524
