### ISSUE TITLE
How keep watch when Error?

### ISSUE THREAD

**Issue by lizhong8532** [rollup/rollup#1153]
My npm dev command:
```
rollup -w -c build/rollup.dev.config.js
```

rollup.dev.config.js
```
import buble from 'rollup-plugin-buble'

export default {
	entry: 'src/main.js',
	format: 'umd',
	moduleName: 'Graph',
	plugins: [
		buble()
	],
	dest: 'dist/ugraph.js'
}
```

If compile success each should be okay, but when compile has error so can't no keep watch file after change file, 

Current solution manual reload npm command when rullopjs compile error

Who can help please!

**Comment by vinkla** [comment]
I can also confirm this. Usually after getting an error it stops watching and sometimes it trigger this error afterwards:

```sh
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
```

**Comment by Rich-Harris** [comment]
Fixed in 0.39.2 – thanks

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
Thanks @Rich-Harris! Just upgraded and it keeps watching. Though, once it fails it still returns `Maximum call stack size exceeded` even after I've fixed the error. Do you think my error could be related to this issue?

If not, then I'll open a new issue with more details.

**Comment by vinkla** [comment]
Thanks @Rich-Harris!

**Comment by lizhong8532** [comment]
@Rich-Harris You are good man. very love you!

**Comment by mattzuba** [comment]
@Rich-Harris - #1205 didn't seem to solve the original issue here for me.  If rollup (or a plugin for rollup) encounters an error, I don't get the Maximum call stack size exceeded error, but once I fix the code issue, rollup doesn't attempt to recompile either, but the watch process is still running.  I have to stop the watch and restart it for it to recompile and continue watching for changes.

**Comment by rpjohnst** [comment]
Anyone still watching this bug: it seems rollup/rollup-watch#38 is the real problem at this point.

**Comment by Finesse** [comment]
@Rich-Harris Watching still stops when an error occurs during the first bundling. If the same error occurs in a next bundling, the watch is kept.
