### ISSUE TITLE
Including images

### ISSUE THREAD

**Issue by martinwells** [rollup/rollup#1309]
Maybe a newb question, but I'm having real trouble figuring out how you include image files into the bundle? Can't seem to find any examples, and the plugins, such as rollup-plugin-rebase and -url all don't seem to work (again, no examples).

Am I missing something obvious here?

(Yes, I've played with rollup-image, but it only base64 encodes images)

**Comment by btd** [comment]
It seems [rollup-plugin-image](https://github.com/rollup/rollup-plugin-image) is doing exactly what are you talking.
It takes image, create data uri for it, and manually constact image like:
```
var img = new Image();
img.src = DATA_URI_THERE
```
And you can do next with this `img` what you wnat - it is DOM node.

**Comment by martinwells** [comment]
Thanks for the reply.

However, afaiw this bundles the image as data (base64). Whereas I'm just
after including it. Maybe all I need is a way to copy image files to the
dist directory?

**Comment by btd** [comment]
I think rollup is not right thing there. Rollup purpose to combine js files (written using modules), rollup plugins just convert files to js with modules, and give them back to rollup for processing. So while you can do this from inside rollup plugin, but i would recommend you try another options, like gulp (if you only want to move files).

**Comment by martinwells** [comment]
Yep. OK. I ended up just rsyncing the files and directly referencing. Thanks.

**Comment by alwaysonlinetxm** [comment]
@martinwells I think you may need this [rollup-plugin-img](https://github.com/alwaysonlinetxm/rollup-plugin-img)

**Comment by arvinsim** [comment]
I tried [rollup-plugin-img](https://github.com/alwaysonlinetxm/rollup-plugin-img) but it doesn't work.

**Comment by lukastaegert** [comment]
If there is no plugin that suits your needs, maybe directly using the plugin API will help you. A lot has happened here since 2017. The example here https://rollupjs.org/guide/en/#file-urls should be very close to what you need, and it is only a few lines of code. Also you will learn something about plugins.

**Comment by arvinsim** [comment]
@lukastaegert Unfortunately, the task I am on is time sensitive. If the deadline will be delayed, I can try to learn the rollup plugins. But if not then I will have to switch to another solution.

**Comment by lukastaegert** [comment]
If rollup-plugin-img does not work then you should probably tell them that is the case instead of writing in closed tickets, but I see not issue opened by you in that repo. Also, you did not specify what your issues are and what you are trying to do, but as I am also on a very tight budget time-wise, my feeling is just looking at the documentation I linked you to might be your quickest way to success. It's not rocket science.

**Comment by CrashyBang** [comment]
Hey @arvinsim ,

Handling images is very easy via the [url](https://github.com/rollup/plugins/tree/master/packages/url) plugin, a basic example looks something like:

```
import url from '@rollup/plugin-url';

export default {
        input: "module.js",
        output: { /* output config */ },
        plugins: [
                url({
                        // Where to put files
                        destDir: 'dist/assets/',
                        // Path to put infront of files (in code)
                        publicPath: process.env.NODE_ENV === "development"
                                ? 'http://localhost:8000/dist/assets/'
                                : './assets/',
                        // File name once copied
                        fileName: '[name][extname]',
                        // Kinds of files to process
                        include: [
                                '**/*.svg',
                                '**/*.png',
                                '**/*.gif',
                                '**/*.jpg',
                                '**/*.jpeg',
                        ]
                }),
        ]
}
```

You can also set `limit: 0` if you want *all images* to be copied.

**Comment by arvinsim** [comment]
@CrashyBang I am using it in [tsdx](https://github.com/jaredpalmer/tsdx) and I get a `(typescript) Error: Unknown object type "asyncfunction"`

**Comment by shellscape** [comment]
Done! https://repl.it/@rollup/rollup-repro

**Comment by PlkMarudny** [comment]
This does not work for css, fonts for example:

````
<script>
import CorporateFont from "./assets/fonts/BloombergArabicBetav4-Regular.woff";
...
</script>
...

<style>
@font-face {
    font-family: "Bloomberg Arabic Beta v4";
    src: url({CorporateFontBold}) format("woff");
    font-weight: bold;
    font-style: normal;
  }
...
</style>
````

**Comment by SivaGanesh56** [comment]
i tired all above apporaches. nothing worked for me

**Comment by Abhikumar98** [comment]
Hey,
Facing similar issue with svgs.

The svgs are being converted to base64 and this fails in safari browsers.

So, trying to keep the svg files static and imports right accordingly.

**Comment by hanifmhd** [comment]
> Hey @arvinsim ,
> 
> Handling images is very easy via the [url](https://github.com/rollup/plugins/tree/master/packages/url) plugin, a basic example looks something like:
> 
> ```js
> import url from '@rollup/plugin-url';
> 
> export default {
>         input: "module.js",
>         output: { /* output config */ },
>         plugins: [
>                 url({
>                         // Where to put files
>                         destDir: 'dist/assets/',
>                         // Path to put infront of files (in code)
>                         publicPath: process.env.NODE_ENV === "development"
>                                 ? 'http://localhost:8000/dist/assets/'
>                                 : './assets/',
>                         // File name once copied
>                         fileName: '[name][extname]',
>                         // Kinds of files to process
>                         include: [
>                                 '**/*.svg',
>                                 '**/*.png',
>                                 '**/*.gif',
>                                 '**/*.jpg',
>                                 '**/*.jpeg',
>                         ]
>                 }),
>         ]
> }
> ```
> 
> You can also set `limit: 0` if you want _all images_ to be copied.

I still face error `(!) Plugin typescript: @rollup/plugin-typescript TS2307: Cannot find module './edit.png' or its corresponding type declarations.
src/assets/icons/index.ts: (18:22)`

anyone know how to solve this?

**Comment by tonyschwebach** [comment]
@olefrank  what solution did you find for this?
> 
> How do you reference the images in react components with this? I tried this and get GET 404 on all images in /assets folder...
