### ISSUE TITLE
Question: Separation of dependency resolution?

### ISSUE THREAD

**Issue by phated** [rollup/rollup#1834]
I was talking with @guybedford about the possibility of utilizing the dependency graph resolution code separate from the generation code (though it might still be useful to pass it to the rollup generator after analysis) and he said that current code wasn't implemented with that in mind.

Do you think it would be possible to expose the API or split the graph traversal/resolution into a separate module?

**Comment by guybedford** [comment]
I feel like discussions like this are worth having as one of my main motivations for contributing into Rollup over writing a separate project was to ensure that this kind of analysis wouldn't be duplicated in managing code splitting workflows when also using Rollup anyway in such workflows.

We can already have AST code sharing with the AST return in plugins, which would support custom dependency analysis being run.

Dependency analysis to determine the list of dependencies and load those separately is relatively straightforward to write custom.

What is harder to write custom is the exact resolution semantics of being able to link import/export bindings to their variable instances.

@phated perhaps you could share a little more on which parts of the above use cases you are after.

This may likely not have any easy solutions, but it feels like a good discussion to have as if there were any way to open up these fundamentals of Rollup further that only feels like it could be a win to the ecosystem.

**Comment by phated** [comment]
I'm hoping to resolve globs (e.g. `src/entries/*.js`) to a dependency graph with each being an entry file.  It seems like I can get relevant information by calling `rollup(config)` and accessing `.imports`, `.exports` and `.modules` on the "build" object but there's a bunch of extra stuff that isn't needed for my analysis pipeline (don't need generation or plugins, etc) and I'm not sure if those properties are spec'd.

**Comment by guybedford** [comment]
I personally think it would be very cool if Rollup could be broken up as a compiler that exposes its internals more for these sorts of low-level use cases, but it's a very hard thing to get right in terms of API stability.

One thing Rollup does at the moment is conflate a lot of meanings in the classes. For example the Module class represents both a source module, connects into the AST Nodes of a source module, and represents the linkage of that source module. An AST Node is not just a Node, but contains scoping information specific to the graph linkage, as well as rendering information and deshadowing information etc etc.

Getting to a place where these concerns are separated into different layers might then allow a more abstract concept of building up a dependency graph without cross-cutting concerns. And some explorations here could be interesting.

Say for example:

```js
import { Graph } from 'rollup';

const graph = new Graph(basePath);
graph.setPlugins(...);

graph.loadEntry('./asdf/*.js');

for (let module of graph.modules) {
  console.log(module.dependencies);
}
```

Getting to a place where this API is clean enough to expose outwardly would be very interesting, and the act of working out such an API would also clean up the `Module` class public interface, naturally creating the separations of AST, scoping, deshadowing, rendering that should be treated as other layers.

Also a better separation of concerns could lead to more caching opportunities between layers etc etc.

Would be interesting to hear what others think, and if these API levels are worth pursuing.

**Comment by lukastaegert** [comment]
I would love this! Personally, I would also like to be able to extract the tree-shaking at some point (like, to be able to have a `webpack-plugin-rollup-treeshaking` 😜).

I have also been in recent talks with @kellyselden and @twokul who work on ember-cli and are currently maintaining a fork of rollup that just does the module resolution and tree-shaking, but not the bundling (they basically render the same files with some code stripped out). It would be great if we could support them by providing some "official" APIs that they could hook into.

And yes, before we do this we should seriously slim down our internal APIs.

**Comment by kellyselden** [comment]
For example, right now I export Bundle.js alongside rollup/index.js in my rollup fork. I just use the `build` function of Bundle.js. Then I ignore the `render` function and do all the rendering myself, via `Module.render()`.

**Comment by phated** [comment]
@guybedford I'm poking at this today a little.  I'm going to search for the things you mention but do you have anywhere you can point me?

**Comment by phated** [comment]
@guybedford it looks like I lose the AST when I run `generate()`.  Is that the expected result?

**Comment by guybedford** [comment]
@phated yes the AST isn't exposed on this API, because we decorate it with a lot of private methods that aren't part of the versioned API of the project.

**Comment by phated** [comment]
@guybedford Interesting, I was hoping to have that AST to pass along in a pipeline and avoid any extra AST parses (like is often found in webpack plugins) - would you suggest I do a separate acorn.parse or is there a way we could resolve that?

**Comment by guybedford** [comment]
Right, it may be better to utilize a custom dependency extraction in those cases then. It may even be straightforward even to fork the code here and remove all the other rollup stuff to get what you need. Feel free!

**Comment by phated** [comment]
Sounds good.  I believe the resolution mentioned in my initial comment has been solved.  I'll close this but feel free to re-open if you don't feel like it is completely solved.

**Comment by eight04** [comment]
Never know that `experimentalPreserveModules` exists. Is it documented?

**Comment by lukastaegert** [comment]
@eight04 Unfortunately not in the official documentation yet. It IS one of the more experimental features but it is stabilizing. It is rather easy to use: #1922

@phated 
> yes the AST isn't exposed on this API, because we decorate it with a lot of private methods that aren't part of the versioned API of the project

This is true but we still have the original, unmodified AST available as well which we use to make watch mode a little faster. So it would be possible to provide it with a little extra effort. The intention, however, was to reduce the API surface but this could be extended if we can make up our minds about a good API.
