### ISSUE TITLE
Named export not resolving when converting to cjs

### ISSUE THREAD

**Issue by theetrain** [rollup/rollup#3011]
- Rollup Version: 1.14.1
- Operating System (or Browser): macOS Mojave 10.14.5
- Node Version: 8.11.3

### How Do We Reproduce?

When I import the `withTheme` module from [styled-components](https://github.com/styled-components/styled-components) and build my code to cjs format, Rollup assumes `withTheme` it is included as part of the default export. I'm unsure if the underlying issue is with how styled-components exports their modules, or how Rollup resolves them; I would appreciate some pointers if that's the case. 

[REPL with the issue](https://rollupjs.org/repl/?version=1.16.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHN0eWxlZCUyQyUyMCU3QiUyMHdpdGhUaGVtZSUyMCU3RCUyMGZyb20lMjAnc3R5bGVkLWNvbXBvbmVudHMnJTVDbiU1Q25jb25zdCUyME15Q29tcG9uZW50JTIwJTNEJTIwc3R5bGVkLmRpdiglN0Jjb2xvciUzQSUyMCd3aGl0ZSclN0QpJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwd2l0aFRoZW1lKE15Q29tcG9uZW50KSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE).
```js
import styled, { withTheme } from 'styled-components'
```

[REPL with a workaround](https://rollupjs.org/repl/?version=1.16.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHN0eWxlZCUyMGZyb20lMjAnc3R5bGVkLWNvbXBvbmVudHMnJTVDbmNvbnN0JTIwd2l0aFRoZW1lJTIwJTNEJTIwcmVxdWlyZSgnc3R5bGVkLWNvbXBvbmVudHMnKS53aXRoVGhlbWUlNUNuJTVDbmNvbnN0JTIwTXlDb21wb25lbnQlMjAlM0QlMjBzdHlsZWQuZGl2KCU3QmNvbG9yJTNBJTIwJ3doaXRlJyU3RCklNUNuJTVDbmV4cG9ydCUyMGRlZmF1bHQlMjB3aXRoVGhlbWUoTXlDb21wb25lbnQpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).
```js
import styled from 'styled-components'
const withTheme = require('styled-components').withTheme
```

This is [how styled-components is shipped](https://unpkg.com/styled-components@4.3.2/dist/styled-components.cjs.js) (scroll to the bottom to see modules).
```js
exports.default = styled;
...
exports.withTheme = withTheme;
```

I also attempted to make use of `namedExports` in my Rollup config, but to no avail. 

```js
{
  plugins: [
      commonjs({
        include: '../../node_modules/**',
        namedExports: {
          'styled-components': ['withTheme']
        }
      })
  ]
}
```

### Expected Behavior

`withTheme` is imported as a named export from `styled-components`.

### Actual Behavior

`withTheme` is assumed as an object key in the default export of `styled-components`.

**Comment by TrySound** [comment]
I don't understand the problem here. withTheme is accessed from `styled` namespace. Default export is resolved to styled__default.

```js
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var styled = require('styled-components');
var styled__default = _interopDefault(styled);

const MyComponent = styled__default.div({color: 'white'});

var main = styled.withTheme(MyComponent);

module.exports = main;
```

**Comment by agorovyi** [comment]
This issue seems to be related to what was reported here: https://github.com/styled-components/babel-plugin-styled-components/issues/216

What I learned today was that our build works fine for ES Modules but doesn't resolve named exports correctly for CommonJS: https://github.com/styled-components/babel-plugin-styled-components/issues/216#issuecomment-516009831

**Comment by agorovyi** [comment]
> I don't understand the problem here. withTheme is accessed from `styled` namespace. Default export is resolved to styled__default.
> 
> ```js
> 'use strict';
> 
> function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }
> 
> var styled = require('styled-components');
> var styled__default = _interopDefault(styled);
> 
> const MyComponent = styled__default.div({color: 'white'});
> 
> var main = styled.withTheme(MyComponent);
> 
> module.exports = main;
> ```

The problem here is that `withTheme` is accessed through it's own named export and not through `styled` namespace.

This output will throw this error: `styled.withTheme is not a function`.

The correct output should be `var main = withTheme(MyComponent);`

This is how it's resolved in `esm` in [this REPL](https://rollupjs.org/repl/?version=1.16.4&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMHN0eWxlZCUyQyUyMCU3QiUyMHdpdGhUaGVtZSUyMCU3RCUyMGZyb20lMjAnc3R5bGVkLWNvbXBvbmVudHMnJTVDbiU1Q25jb25zdCUyME15Q29tcG9uZW50JTIwJTNEJTIwc3R5bGVkLmRpdiglN0Jjb2xvciUzQSUyMCd3aGl0ZSclN0QpJTVDbiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwd2l0aFRoZW1lKE15Q29tcG9uZW50KSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)

**Comment by TrySound** [comment]
I still don't see the problem with rollup. What is the right way? What is wrong with `require('styled-components').withTheme`?

**Comment by TrySound** [comment]
You showed me this workaround
```js
const withTheme = require('styled-components').withTheme
```
How is it different from what rollup is generated?
```js
var styled = require('styled-components');
styled.withTheme
```

**Comment by theetrain** [comment]
Hello again, apologies for not providing enough context. I have a more detailed write-up here: https://github.com/styled-components/babel-plugin-styled-components/issues/216#issuecomment-516941240

In summary:

- Styled components has a default export `styled` and named exports `keyframes` and `withTheme` that we would like to use
- When using ES2015 import statement `import styled, { keyframes } from 'styled-components'`, Rollup transpiles to CJS format
   ```js
   var styled = require('styled-components');
   var styled__default = _interopDefault(styled);

   ...
   var spinnerRotate = styled.keyframes(["100%{transform:rotate(360deg);}"]);
  ```
- For some reason, when the CJS file calls `styled.keyframes`, it throws an error: `styled.keyframes.withConfig is not a function` as though `keyframes` is not defined. I have not yet debugged this line to confirm 100%.

>How is it different from what rollup is generated?
>
>```
>var styled = require('styled-components');
>styled.withTheme
>```

@TrySound I agree, calling `withTheme` as `styled.withTheme` is no different than extracting it ahead of time with `var withTheme = require('styled-components').withTheme`. Yet, when I extract a named export ahead of time, the error is not thrown. 

I'm not sure what the underlying issue is, and I don't fully suspect the issue is with Rollup, but I'll try to keep the conversation between here and the `styled-components` community once someone can help provide insight or when I take a moment to debug this deeper.

I appreciate your patience and support. 👍

**Comment by daraclare** [comment]
I'm getting the same issue when using rollup through tsdx, is there a workaround that doesn't involve changing how we import `withTheme` or `css` or `keyframes` from styled components? We're moving a large file base, so would be painful to change all the imports. Also, it seems wrong to not be able to use `import styled, { withTheme } from 'styled-components'`

**Comment by adrianObel** [comment]
Were you able to find a solution? I'm facing the same problem but when importing `css` from styled-components.

**Comment by shellscape** [comment]
@lukastaegert it looks like this one is still valid. I can't quite see what the issue would be. Here;'s the result from `require('styled-components')`:

```js
{
  default: [Function: styled] {
    a: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    abbr: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    address: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    area: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    article: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    aside: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    audio: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    b: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    base: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    bdi: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    bdo: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    big: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    blockquote: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    body: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    br: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    button: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    canvas: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    caption: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    cite: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    code: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    col: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    colgroup: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    data: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    datalist: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    dd: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    del: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    details: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    dfn: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    dialog: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    div: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    dl: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    dt: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    em: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    embed: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    fieldset: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    figcaption: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    figure: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    footer: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    form: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    h1: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    h2: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    h3: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    h4: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    h5: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    h6: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    head: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    header: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    hgroup: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    hr: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    html: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    i: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    iframe: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    img: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    input: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    ins: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    kbd: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    keygen: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    label: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    legend: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    li: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    link: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    main: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    map: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    mark: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    marquee: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    menu: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    menuitem: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    meta: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    meter: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    nav: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    noscript: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    object: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    ol: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    optgroup: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    option: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    output: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    p: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    param: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    picture: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    pre: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    progress: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    q: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    rp: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    rt: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    ruby: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    s: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    samp: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    script: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    section: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    select: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    small: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    source: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    span: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    strong: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    style: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    sub: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    summary: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    sup: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    table: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    tbody: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    td: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    textarea: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    tfoot: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    th: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    thead: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    time: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    title: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    tr: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    track: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    u: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    ul: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    var: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    video: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    wbr: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    circle: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    clipPath: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    defs: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    ellipse: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    foreignObject: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    g: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    image: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    line: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    linearGradient: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    marker: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    mask: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    path: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    pattern: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    polygon: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    polyline: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    radialGradient: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    rect: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    stop: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    svg: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    text: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    },
    tspan: [Function: templateFunction] {
      withConfig: [Function],
      attrs: [Function]
    }
  },
  createGlobalStyle: [Function: createGlobalStyle],
  css: [Function: css],
  isStyledComponent: [Function: isStyledComponent],
  keyframes: [Function: keyframes],
  ServerStyleSheet: [Function: ServerStyleSheet],
  StyleSheetConsumer: {
    '$$typeof': Symbol(react.context),
    _context: {
      '$$typeof': Symbol(react.context),
      _calculateChangedBits: null,
      _currentValue: undefined,
      _currentValue2: undefined,
      _threadCount: 0,
      Provider: [Object],
      Consumer: [Circular],
      _currentRenderer: null,
      _currentRenderer2: null
    },
    _calculateChangedBits: null
  },
  StyleSheetContext: {
    '$$typeof': Symbol(react.context),
    _calculateChangedBits: null,
    _currentValue: undefined,
    _currentValue2: undefined,
    _threadCount: 0,
    Provider: { '$$typeof': Symbol(react.provider), _context: [Circular] },
    Consumer: {
      '$$typeof': Symbol(react.context),
      _context: [Circular],
      _calculateChangedBits: null
    },
    _currentRenderer: null,
    _currentRenderer2: null
  },
  StyleSheetManager: [Function: StyleSheetManager] {
    propTypes: { sheet: [Function], target: [Function] }
  },
  ThemeConsumer: {
    '$$typeof': Symbol(react.context),
    _context: {
      '$$typeof': Symbol(react.context),
      _calculateChangedBits: null,
      _currentValue: undefined,
      _currentValue2: undefined,
      _threadCount: 0,
      Provider: [Object],
      Consumer: [Circular],
      _currentRenderer: null,
      _currentRenderer2: null
    },
    _calculateChangedBits: null
  },
  ThemeContext: {
    '$$typeof': Symbol(react.context),
    _calculateChangedBits: null,
    _currentValue: undefined,
    _currentValue2: undefined,
    _threadCount: 0,
    Provider: { '$$typeof': Symbol(react.provider), _context: [Circular] },
    Consumer: {
      '$$typeof': Symbol(react.context),
      _context: [Circular],
      _calculateChangedBits: null
    },
    _currentRenderer: null,
    _currentRenderer2: null
  },
  ThemeProvider: [Function: ThemeProvider],
  withTheme: [Function: withTheme],
  __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS: { StyleSheet: [Function: StyleSheet] { reset: [Function: reset] } }
}
```
