### ISSUE TITLE
Invalid dead code removal for return statement due to ASI

### ISSUE THREAD

**Issue by evanw** [rollup/rollup#3729]
- Rollup Version: 2.26.0
- Operating System (or Browser): Chrome 84
- Node Version (if applicable):
- Link to reproduction (IMPORTANT, read below): [repl link](http://rollupjs.org/repl/?version=2.26.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmZ1bmN0aW9uJTIwZm9vKCklMjAlN0IlNUNuJTIwJTIwcmV0dXJuJTIwZmFsc2UlMjAlN0MlN0MlNUNuJTIwJTIwJTIwJTIwdHJ1ZSUyMCU3QyU3QyUyMCU1Q24lMjAlMjAlMjAlMjBmYWxzZSU1Q24lN0QlNUNuY29uc29sZS5sb2coZm9vKCkpJTNCJTVDbiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

Input:

```js
function foo() {
  return false ||
    true || 
    false
}
console.log(foo());
```

### Expected Behavior

```js
function foo() {
  return true
}
console.log(foo());
```

### Actual Behavior

```js
function foo() {
  return 
    true 
}
console.log(foo());
```

A function which returns true is incorrectly transformed into a function which returns undefined. This is a reduced test case from real-world code [here](https://unpkg.com/styled-components@5.1.1/dist/styled-components.cjs.js) that looks like this:

```js
function getComponentName(target) {
  return (process.env.NODE_ENV !== 'production' ? typeof target === 'string' && target : false) || // $FlowFixMe
  target.displayName || // $FlowFixMe
  target.name || 'Component';
}
```

**Comment by kzc** [comment]
Similar ASI issues are also present in `throw` and `yield`...

**throw**
```
$ cat throw.js
process.on("uncaughtException", x => console.log(x.message))
throw null ||
    new Error("PASS") ||
    false
```
expected:
```
$ cat throw.js | node
PASS
```
actual:
```
$ cat throw.js | dist/bin/rollup --silent
process.on("uncaughtException", x => console.log(x.message));
throw 
    new Error("PASS") ||
    false
```
```
$ cat throw.js | dist/bin/rollup --silent | node
[stdin]:2
throw 
^^^^^

SyntaxError: Illegal newline after throw
```

**yield**

```
$ cat yield.js 
function* f(x) {
    yield 0 ||
        x
}
let iter = f(5)
console.log(iter.next().value)
```
expected:
```
$ cat yield.js | node
5
```
actual:
```
$ cat yield.js | dist/bin/rollup --silent
function* f(x) {
    yield 
        x;
}
let iter = f(5);
console.log(iter.next().value);
```
```
$ cat yield.js | dist/bin/rollup --silent | node
undefined
```

I didn't investigate whether `await` has the same issue.

**Comment by lukastaegert** [comment]
Thanks for spotting, I will have a look. I know I already fixed a similar group of issues in #3035 but apparently I missed something 🙄

**Comment by lukastaegert** [comment]
Ah I see, I forgot to pass down the preventASI flag for nested expressions... Fix at #3732

**Comment by kzc** [comment]
@lukastaegert PR #3732 does not address the ASI bug in `throw` - see https://github.com/rollup/rollup/issues/3729#issuecomment-674464198.

**Comment by kzc** [comment]
There's also still an issue with `yield` ...

```
$ dist/bin/rollup -v
rollup v2.26.2
```
```
$ cat yield2.js
function* f(x) {
    yield 0 ||
        x ||
        false
}
let iter = f("PASS")
console.log(iter.next().value)
```
expected:
```
$ cat yield2.js | node
PASS
```
actual:
```
$ cat yield2.js | dist/bin/rollup --silent
function* f(x) {
    yield 
        x ||
        false;
}
let iter = f("PASS");
console.log(iter.next().value);
```
```
$ cat yield2.js | dist/bin/rollup --silent | node
undefined
```

**Comment by lukastaegert** [comment]
Ah I see, I did not consider that due to execution order, the AST is nested so the first logical expression is nested into the second one, not the other way around. So if the second one is indeterminate, the first one could still be simplified to cause the issue, but the preventASI flag needs to be passed through the second one.

> I didn't investigate whether await has the same issue.

I do not think so because I am quite sure that there is no ASI after `await`. I think I assumed the same for `yield` but apparently that assumption was wrong.
