### ISSUE TITLE
How can i use like webpackChunkName annotations in rollup to assign chunk name?

### ISSUE THREAD

**Issue by zhangyuang** [rollup/rollup#4283]
How can i use like webpackChunkName annotations in rollup to assign chunk name? Or, where i can get import annotations like `import(/* webpackChunkName*   path/)` in rollup

**Comment by FoxDaxian** [comment]
try [this](https://rollupjs.org/guide/en/#outputmanualchunks)?
maybe it can do what you want

**Comment by zhangyuang** [comment]
> try [this](https://rollupjs.org/guide/en/#outputmanualchunks)? maybe it can do what you want

I have try it, but manualChunks provide moduleInfo without import annotations

**Comment by FoxDaxian** [comment]
I think `acorn` do not support annotations node type.
![image](https://user-images.githubusercontent.com/19708789/143440561-e5d22944-7f80-402b-8f54-7494f14c15ab.png)

maybe need some acorn|rollup plugins to support this.
![image](https://user-images.githubusercontent.com/19708789/143440735-6de8d009-fdc2-4c75-9421-16f5fce42a55.png)

**Comment by zhangyuang** [comment]
Thanks, now i have try implement it by `es-module-lexer`

**Comment by FoxDaxian** [comment]
cool~ 
looking forward to your sharding~

**Comment by zhangyuang** [comment]
I have implemented it by below code

```js
import { parse as parseImports } from 'es-module-lexer'

const webpackCommentRegExp = /webpackChunkName:\s"(.*)?"/

// transform import(/* webpackChunkName: foo */ foo.js) => import(/* webpackChunkName: foo */ foo.js?chunkName=foo)
// and we can get chunkName params in manuanlChunks
const myPlugin: Plugin = () => {
  return {
    name: 'transform-file',
    transform (source, id) {
      if (id.includes('ssr-temporary-routes')) {
        let str = new MagicString(source)
        const imports = parseImports(source)[0]
        for (let index = 0; index < imports.length; index++) {
          const { s: start, e: end } = imports[index]

          const rawUrl = source.slice(start, end)
          if (!rawUrl.includes('render')) continue
          const chunkName = webpackCommentRegExp.exec(rawUrl)![1]
          str = str.appendRight(end - 1, `?chunkName=${chunkName}`)
        }
        return {
          code: str.toString()
        }
      }
    }
  }
}
  manualChunks: (id) => {
   console.log(id) // /xxxfile?chunkName=foo

}
    

```

**Comment by thetime50** [comment]
> 我已经通过下面的代码实现了它
> 
> ```js
> import { parse as parseImports } from 'es-module-lexer'
> 
> const webpackCommentRegExp = /webpackChunkName:\s"(.*)?"/
> 
> // transform import(/* webpackChunkName: detail */ "@/detail/render.vue") => import(/* webpackChunkName: detail */ @/detail/render.vue?chunkName=detail)
> // and we can get chunkName params in manuanlChunks
> const myPlugin: Plugin = () => {
>   return {
>     name: 'transform-file',
>     transform (source, id) {
>       if (id.includes('ssr-temporary-routes')) {
>         let str = new MagicString(source)
>         const imports = parseImports(source)[0]
>         for (let index = 0; index < imports.length; index++) {
>           const { s: start, e: end } = imports[index]
> 
>           const rawUrl = source.slice(start, end)
>           if (!rawUrl.includes('render')) continue
>           const chunkName = webpackCommentRegExp.exec(rawUrl)![1]
>           str = str.appendRight(end - 1, `?chunkName=${chunkName}`)
>         }
>         return {
>           code: str.toString()
>         }
>       }
>     }
>   }
> }
>   manualChunks: (id) => {
>    console.log(id) // pages/detail/render$id.vue?chunkName=detail-id
> 
> }
>     
> ```

thanks,is works，But using the file in node_modules will report an error，i don't know what to do

```
[vite]: Rollup failed to resolve import "vue3-lottie?chunkName=vue-lottie" from "src/pages/demo/demo.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "vue3-lottie?chunkName=vue-lottie" from "src/pages/demo/demo.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (D:\work\ytt-pc-1\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:41772:19)
    at onwarn (D:\work\ytt-pc-1\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:41588:13)
    at Object.onwarn (D:\work\ytt-pc-1\node_modules\rollup\dist\shared\rollup.js:23224:13)
    at ModuleLoader.handleResolveId (D:\work\ytt-pc-1\node_modules\rollup\dist\shared\rollup.js:22508:26)
    at ModuleLoader.resolveDynamicImport (D:\work\ytt-pc-1\node_modules\rollup\dist\shared\rollup.js:22560:120)
    at D:\work\ytt-pc-1\node_modules\rollup\dist\shared\rollup.js:22455:32
```

**Comment by zhangyuang** [comment]
It looks like there lack file extensions

**Comment by zhangyuang** [comment]
Maybe you should add querystring after module entry file like `vue3-lottie/dist/index.js?chunkName=xxx`

**Comment by thetime50** [comment]
I tried it, but it still doesn't work

`
const Vue3LottieImport = async () => (
  (await import(/* webpackChunkName: "vue-lottie" */ "vue3-lottie/dist/index.js")).Vue3Lottie
);
`

`
[vite:resolve] Missing "./dist/index.js" export in "vue3-lottie" package
error during build:
Error: Missing "./dist/index.js" export in "vue3-lottie" package
`

**Comment by FoxDaxian** [comment]
> I tried it, but it still doesn't work
> 
> `const Vue3LottieImport = async () => ( (await import(/* webpackChunkName: "vue-lottie" */ "vue3-lottie/dist/index.js")).Vue3Lottie );`
> 
> `[vite:resolve] Missing "./dist/index.js" export in "vue3-lottie" package error during build: Error: Missing "./dist/index.js" export in "vue3-lottie" package`

It looks like vue3-lottie not exports something like './dist/index.js', maybe you can check it and do some optimize

**Comment by tyhyly** [comment]
you can try as below:
```js
rollupOptions: {
   output: {
     manualChunks(id: string) {
            if (id.includes('src/pages/A')) {
              return 'A'; // this name can be defined by yourself
            }
       
            if (id.includes('node_modules/lodash-es')) {
              return "lodash-es-x";
            }
          }
    }
}
```
